### ISSUE TITLE
关于windows下gcc编译问题

### ISSUE THREAD

**Issue by ExcaliburEX** [drmingdrmer/lrc-erasure-code#3]
@drmingdrmer  您好，非常感谢您分享的C语言实现的LRC编码！我在windows下实践中产生了一些问题，不知您在百忙之中可否帮忙查看一下~
# Ubuntu 
可以使用，编译成功！
# Windows
因为我想用`Go`语言的`CGO`接口，通过一系列编译指令，将所有`*.o`文件，联合编译成一个`*.a`静态库文件，在`Go`中调用这个静态库文件，实现LRC的`Go`语言实现版本。我将`Ubuntu`上已经实现了我所想要达到的效果。

但是`Ubuntu`上生成的静态编译文件（`*.a`文件）在`Windows`上并不能使用，会报错：
```shell
F:\go\src\LRC>go run main.go
# command-line-arguments
C:\Users\kemo\AppData\Local\Temp\go-build401154902\b001\_x002.o: In function `_cgo_63f49bbaaa19_Cfunc_lrc_buf_init':
/tmp/go-build/cgo-gcc-prolog:80: undefined reference to `lrc_buf_init'
C:\Users\kemo\AppData\Local\Temp\go-build401154902\b001\_x002.o: In function `_cgo_63f49bbaaa19_Cfunc_lrc_decode':
/tmp/go-build/cgo-gcc-prolog:101: undefined reference to `lrc_decode'
C:\Users\kemo\AppData\Local\Temp\go-build401154902\b001\_x002.o: In function `_cgo_63f49bbaaa19_Cfunc_lrc_encode':
/tmp/go-build/cgo-gcc-prolog:133: undefined reference to `lrc_encode'
C:\Users\kemo\AppData\Local\Temp\go-build401154902\b001\_x002.o: In function `_cgo_63f49bbaaa19_Cfunc_lrc_init_n':
/tmp/go-build/cgo-gcc-prolog:157: undefined reference to `lrc_init_n'
C:\Users\kemo\AppData\Local\Temp\go-build401154902\b001\_x002.o: In function `_cgo_63f49bbaaa19_Cfunc_lrc_buf_destroy':
/tmp/go-build/cgo-gcc-prolog:62: undefined reference to `lrc_buf_destroy'
C:\Users\kemo\AppData\Local\Temp\go-build401154902\b001\_x002.o: In function `_cgo_63f49bbaaa19_Cfunc_lrc_destroy':
/tmp/go-build/cgo-gcc-prolog:116: undefined reference to `lrc_destroy'
collect2.exe: error: ld returned 1 exit status
```
也就是找不到定义，所以我的思考是直接在`Windows`上编译生成静态编译文件。

我的操作流程就是将`/include`和`/src`文件夹里面所有的`*.c`和`*.h`文件全部挪到一个文件夹下，然后使用：
```shell
gcc -c ./*.c
```
编译所有的`*.c`文件生成`*.o`文件，然后出现了下列错误：
```shell
C:\Users\kemo\Desktop\fsdownload\lrc-erasure-code\src>gcc -std=c11 -c ./*.c
./gf.c: In function 'gf_set_region_data':
./gf.c:805:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   uls = (unsigned long) src;
         ^
./gf.c:806:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   uld = (unsigned long) dest;
         ^
./gf.c:829:53: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     fprintf(stderr, "Src = 0x%lx.  Dest = 0x%lx\n", (unsigned long) src,
                                                     ^
./gf.c:830:13: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             (unsigned long) dest);
             ^
./gf.c:837:53: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     fprintf(stderr, "Src = 0x%lx.  Dest = 0x%lx\n", (unsigned long) src,
                                                     ^
./gf.c:838:13: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             (unsigned long) dest);
             ^
./gf.c: In function 'gf_multby_zero':
./gf.c:872:3: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   bzero(dest, bytes);
   ^~~~~
./gf.c: In function 'gf_multby_one':
./gf.c:915:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   uls = (unsigned long) src;
         ^
./gf.c:916:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   uld = (unsigned long) dest;
         ^
./gf_general.c: In function 'gf_general_do_region_check':
./gf_general.c:303:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                  (unsigned long) final_target, i, words, xor);
                  ^
./gf_w16.c: In function 'gf_w16_log_zero_init':
./gf_w16.c:1885:3: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   bzero(&(ltd->_antilog_tbl[0]), sizeof(ltd->_antilog_tbl));
   ^~~~~
./gf_w4.c: In function 'gf_w4_single_table_init':
./gf_w4.c:436:3: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   bzero(std->mult, sizeof(uint8_t) * GF_FIELD_SIZE * GF_FIELD_SIZE);
   ^~~~~
./gf_w8.c: In function 'gf_w8_log_init':
./gf_w8.c:793:41: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   if (h->mult_type == GF_MULT_LOG_ZERO) bzero(alt+510, 255);
                                         ^~~~~
./jerasure.c: In function 'jerasure_generate_decoding_schedule':
./jerasure.c:859:9: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
         bzero(ptr, k*w*w*sizeof(int));
         ^~~~~
./liberation.c: In function 'liberation_coding_bitmatrix':
./liberation.c:64:3: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   bzero(matrix, sizeof(int)*2*k*w*w);
   ^~~~~
./lrc.c: In function 'lrc_init_n':
./lrc.c:33:3: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   bzero(lrc, sizeof(*lrc));
   ^~~~~
./lrc.c: In function 'lrc_buf_init':
./lrc.c:372:9: warning: implicit declaration of function 'posix_memalign' [-Wimplicit-function-declaration]
   ret = posix_memalign((void **)&lb->buf, 16,
         ^~~~~~~~~~~~~~
```
从报错中可以看出，找不到`bzero`和`posix_memalign`的实现，网上的答案是要加入<string.h>的头文件，但事实上我无论是在`*.c`和`*.h`加入这个头文件都不凑效。

# 目前我的问题就是这样，`Ubuntu`下生成的静态编译文件`Windows`不能使用，`Windows`下编译不能成功，可否请您不吝赐教，定当不胜感激！

**Comment by drmingdrmer** [comment]
我没在windows下测试过, 如果想要go版本的实现, 建议不要用cgo, 直接用go版本:
https://github.com/templexxx/xrs
https://github.com/templexxx/reedsolomon

<blockquote><img src="https://avatars0.githubusercontent.com/u/13476726?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/templexxx/xrs">templexxx/xrs</a></strong></div><div>Fast and efficient data reconstruction Erasure code, saving about 30% I/O in reconstruction - templexxx/xrs</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/13476726?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/templexxx/reedsolomon">templexxx/reedsolomon</a></strong></div><div>Reed-Solomon Erasure Code engine in Go, could more than 15GB/s per core - templexxx/reedsolomon</div></blockquote>

**Comment by ExcaliburEX** [comment]
> 我没在windows下测试过, 如果想要go版本的实现, 建议不要用cgo, 直接用go版本:
> https://github.com/templexxx/xrs
> https://github.com/templexxx/reedsolomon
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/13476726?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[templexxx/xrs](https://github.com/templexxx/xrs)**Fast and efficient data reconstruction Erasure code, saving about 30% I/O in reconstruction - templexxx/xrs
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/13476726?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[templexxx/reedsolomon](https://github.com/templexxx/reedsolomon)**Reed-Solomon Erasure Code engine in Go, could more than 15GB/s per core - templexxx/reedsolomon

非常感谢答复，这个库我也看到过，不过他好像实现的是RS码，以及其升级版，跟LRC还是有区别的吧？

<blockquote><img src="https://avatars0.githubusercontent.com/u/13476726?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/templexxx/xrs">templexxx/xrs</a></strong></div><div>Fast and efficient data reconstruction Erasure code, saving about 30% I/O in reconstruction - templexxx/xrs</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/13476726?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/templexxx/reedsolomon">templexxx/reedsolomon</a></strong></div><div>Reed-Solomon Erasure Code engine in Go, could more than 15GB/s per core - templexxx/reedsolomon</div></blockquote>

**Comment by drmingdrmer** [comment]
xrs内部实现里有一个lrc, 用的是[hitchhiker算法](https://blog.openacid.com/storage/ec-3/#hitchhiker-ec%E7%AE%97%E6%B3%95) . lrc是hitchhiker的一部分. 如果要单独使用里面的lrc应该不困难. templexxx和我之前一起做ec来着. 如果你需要的话, 我看看能否给出一个直接使用lrc的接口.

这个项目开始没计划支持windows...我自己也对windows下开发不太熟, 如果可以的话, 直接使用go的版本可能最方便了

**Comment by ExcaliburEX** [comment]
> xrs内部实现里有一个lrc, 用的是[hitchhiker算法](https://blog.openacid.com/storage/ec-3/#hitchhiker-ec%E7%AE%97%E6%B3%95) . lrc是hitchhiker的一部分. 如果要单独使用里面的lrc应该不困难. templexxx和我之前一起做ec来着. 如果你需要的话, 我看看能否给出一个直接使用lrc的接口.
> 
> 这个项目开始没计划支持windows...我自己也对windows下开发不太熟, 如果可以的话, 直接使用go的版本可能最方便了

明白了，我再研究一下，如果在不非常麻烦作者的情况下，能给出接口的话那更好啦！

**Comment by drmingdrmer** [comment]
templexxx最近挺忙的. 我实现一版看看:
https://github.com/openacid/erasurecode

也是基于 https://github.com/templexxx/xrs 来修改的. 

<blockquote><img src="https://avatars1.githubusercontent.com/u/23625658?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/openacid/erasurecode">openacid/erasurecode</a></strong></div><div>Fast and efficient data reconstruction Erasure code, saving about 30% I/O in reconstruction - openacid/erasurecode</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/13476726?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/templexxx/xrs">templexxx/xrs</a></strong></div><div>Fast and efficient data reconstruction Erasure code, saving about 30% I/O in reconstruction - templexxx/xrs</div></blockquote>

**Comment by drmingdrmer** [comment]
试了下, 调整还挺繁琐, 原来里面矩阵那块没有暴露接口来修改. 需要改生产矩阵和求逆矩阵的部分.

如果方便的话, 在你的windows开发环境中调整下bzero和posix_memalign的替换, 帮我提个pr吧🤔

**Comment by ExcaliburEX** [comment]
> 试了下, 调整还挺繁琐, 原来里面矩阵那块没有暴露接口来修改. 需要改生产矩阵和求逆矩阵的部分.
> 
> 如果方便的话, 在你的windows开发环境中调整下bzero和posix_memalign的替换, 帮我提个pr吧🤔

真的很感谢费心 🤸‍♀️ ！意思是说我在windows上修复这个问题，生成可用版本嘛？

**Comment by drmingdrmer** [comment]
恩...是的🤔

**Comment by ExcaliburEX** [comment]
> 恩...是的🤔

好滴！我尝试尝试！
